### PR TITLE
Fix handling for non-root path URLs

### PR DESCRIPTION
**Pull request by philippjfr**
Fixes https://github.com/bokeh/bokeh-fastapi/issues/21

### CODE REVIEW

**Comment by MarcSkovMadsen** [comment]
It works for me on my Jupyterhub.

**Comment by MarcSkovMadsen** [comment]
One note is that on my Jupyterhub I need to add `fastapi dev main.py --root-path /NAMESPACE/user/USERNAME/vscode/proxy/8000/` to get the `/docs` endpoint working.

**Comment by MarcSkovMadsen** [comment]
When this is deployed I will try also deploy fastapi Panel apps behind a reverse proxy on our kubernetes cluster. Will be awesome.

**Comment by philippjfr** [comment]
>One note is that on my Jupyterhub I need to add fastapi dev main.py --root-path /NAMESPACE/user/USERNAME/vscode/proxy/8000/ to get the /docs endpoint working. The Panel apps seems unaffected by this and continue to work.

Right, maybe we can note that in our docs as well. This is required on the FastAPI side.

**Comment by pmeier** [comment]
For completion, here is the [documentation](https://fastapi.tiangolo.com/advanced/behind-a-proxy/#behind-a-proxy) on this.

> But then, when you open the integrated docs UI (the frontend), it would expect to get the OpenAPI schema at `/openapi.json`, instead of `/api/v1/openapi.json`.
>
> So, the frontend (that runs in the browser) would try to reach `/openapi.json` and wouldn't be able to get the OpenAPI schema.
>
> Because we have a proxy with a path prefix of `/api/v1` for our app, the frontend needs to fetch the OpenAPI schema at `/api/v1/openapi.json`.

@MarcSkovMadsen Do you want to submit a PR detailing this use case for Jupyter Hub?

**Review by pmeier — APPROVED** [review]
LGTM, thanks Philipp!

**Comment by MarcSkovMadsen** [comment]
FYI. bokeh-fastapi works for me.

I see a missing mini-coi.js though

image

**Comment by MarcSkovMadsen** [comment]
If I wrap in template the favicon cannot be found though.

image

```python
import panel as pn
from fastapi import FastAPI
from panel.io.fastapi import add_application

app = FastAPI()


@app.get("/")
async def read_root():
    return {"Hello": "World"}


@add_application("/panel", app=app, title="My Panel App")
def create_panel_app():
    slider = pn.widgets.IntSlider(name="Slider", start=0, end=10, value=3)
    component = slider.rx() * "⭐"
    return pn.template.FastListTemplate(main=[component])
```

image

**Pull request merged**
